application: ang-days
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /js
  static_dir: js
- url: /bower_components
  static_dir: bower_components
- url: /partials
  static_dir: partials

- url: /css
  static_dir: css

- url: /stylesheets
  static_dir: stylesheets

- url: /tasks
  script: _go_app
