application: ang-days
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: webapp/app/index.html
  upload: webapp/app/(.*\.html)
- url: /bower_components
  static_dir: webapp/app/bower_components
- url: /css
  static_dir: webapp/app/css

- url: /js
  static_dir: webapp/app/js


- url: /stylesheets
  static_dir: stylesheets
- url: /partials
  static_dir: webapp/app/partials/

- url: /.*
  script: _go_app
